// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.sap.demo.git_demo.wd.comp.new1comp.wdp;


/** 
 * This interface provides constants relevant on Web Dynpro Component level
 */
@SuppressWarnings("all")
public interface IConstantNew1Comp {
}
