// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
//
// $JL-GENERATED-SOURCE$
// ---------------------------------------------------------------------------
package com.sap.demo.git_demo.wd.comp.new1comp.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;

/** Interface that is provided to application class. */

@SuppressWarnings("all")
public interface IPrivateNew1CompWindow extends com.sap.demo.git_demo.wd.comp.new1comp.wdp.IPublicNew1CompWindow {

  /*
   * Event Handler identifiers.
   */ 
    
  /** Event handler constant. */
  public static IWDEventHandlerId WD_EVENTHANDLER_ON_PLUG_DEFAULT = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventHandlerId("onPlugDefault", "New1CompWindow", "com.sap.demo.git_demo.wd.comp.new1comp.New1Comp");
  
  /** Declared event handler. */
  void onPlugDefault(IWDCustomEvent wdEvent );

  /** Enumeration of all available action event handlers. */
  public final class WDActionEventHandler extends com.sap.tc.webdynpro.progmodel.gci.impl.GCIActionEventHandlerEnum
  {
    private static final long serialVersionUID = 0x4e40e83e7c170272L;

    private WDActionEventHandler(String value, boolean isValidating, Object[] declaredParameters) {
      super(value, isValidating, declaredParameters);
    }
  }

  /**
   * Creates a new action for this controller.
   * @param eventHandler is the action's event handler with an appropriate signature
   * @param text is the text displayed in the UI element triggering this action
   */
  IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text);

  /**
   * Creates a new action with the given name for this controller.
   * @param eventHandler is the action's event handler with an appropriate signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text);

}
